// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB32dzTKd_RCK-mMBmo1L3ej_7XD4b4dEg',
    appId: '1:986531762965:web:e4a1edbc134faed1c40f1c',
    messagingSenderId: '986531762965',
    projectId: 'fintrack-17e23',
    authDomain: 'fintrack-17e23.firebaseapp.com',
    storageBucket: 'fintrack-17e23.firebasestorage.app',
    measurementId: 'G-N2D0CFC9X4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWxKyd13g75f6HUbFOatGcUIEMaCGksB4',
    appId: '1:986531762965:android:825818252800fc4ac40f1c',
    messagingSenderId: '986531762965',
    projectId: 'fintrack-17e23',
    storageBucket: 'fintrack-17e23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiHREBNGQkj4Jb2J_E0_1UKAq8cUUCnt4',
    appId: '1:986531762965:ios:bec400ad2e6465e1c40f1c',
    messagingSenderId: '986531762965',
    projectId: 'fintrack-17e23',
    storageBucket: 'fintrack-17e23.firebasestorage.app',
    iosBundleId: 'com.example.fintrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiHREBNGQkj4Jb2J_E0_1UKAq8cUUCnt4',
    appId: '1:986531762965:ios:bec400ad2e6465e1c40f1c',
    messagingSenderId: '986531762965',
    projectId: 'fintrack-17e23',
    storageBucket: 'fintrack-17e23.firebasestorage.app',
    iosBundleId: 'com.example.fintrack',
  );
}
